spring:
  datasource:
    url: jdbc:sqlserver://userdatab.database.windows.net:1433;database=employeedb;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: gopalk
    password: Gopal@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191
